### PR TITLE
Add pagination via kwargs for queries which respect maximum-results

### LINKED ISSUE #19: Pagination for all requests which support limits
Based on 
https://developer.atlassian.com/server/crowd/using-the-crowd-rest-apis/#optional-start-index-and-max-results-query-parameters
it should be possible to do paginated queries, in case the resultset is exceedingly large.

Prepping a PR for this.

### PR DESCRIPTION
**Pull request by RPCMoritz**
Allows scaling out queries, without running into issues handling the response.
Fixes #19

### CODE REVIEW

**Comment by RPCMoritz** [comment]
Also took the liberty to version bump, in anticipation of a new release.

**Review by StegSchreck — APPROVED** [review]
lgtm :)

**Comment by m4ce** [comment]
Thanks for your contribution!

**Comment by RPCMoritz** [comment]
Will you be doing a tag-release-cycle for this change?

**Comment by m4ce** [comment]
> Will you be doing a tag-release-cycle for this change?

It's there - 0.0.9!

**Comment by RPCMoritz** [comment]
Still cannot see it here: https://pypi.org/project/crowd-api/

**Comment by m4ce** [comment]
done

**Pull request merged**
