### PR TITLE
Feature/remove group

### PR DESCRIPTION
**Pull request by ch3paz**
Added the ability to delete a group in crowd.

### CODE REVIEW

**Comment by m4ce** [comment]
Thanks for the contribution - can you please remove the .gitignore change from the commit and squash it?

**Comment by ch3paz** [comment]
> 
> 
> Thanks for the contribution - can you please remove the .gitignore change from the commit and squash it?

Shure, i'll try my very best and <s>create a new pullrequest</s> try to squash it ;)

**Comment by m4ce** [comment]
@ch3paz, looks like now the PR will remove the .gitignore entirely. I think you want to remove that change from the PR.

**Comment by ch3paz** [comment]
> 
> 
> @ch3paz, looks like now the PR will remove the .gitignore entirely. I think you want to remove that change from the PR.

Sorry, maybe i'm messing things more up than got an solution. Currently i'm not shure how i can remove the unneeded commits .oO

**Comment by m4ce** [comment]
No worries - I cleaned it up and opened another PR - #16

**Comment by ch3paz** [comment]
@m4ce Thank you!

**Pull request closed without merging**
